name: E2E Historic
on:
  workflow_dispatch:
    inputs:
      runner:
        description: Runner name
        type: string
        required: false
      texlive-version:
        description: TeX Live version
        type: string
        required: false
permissions:
  contents: read
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - uses: actions/checkout@v5
      - if: github.actor == 'nektos/act'
        name: Install jq
        run: |
          apt update
          apt install -y --no-install-recommends jq
      - name: Generate matrix
        id: generate
        run: |
          matrix=$(
            ./scripts/generate-matrix.jq \
              packages/data/data/texlive-versions.json
          )
          echo "matrix=${matrix}" >>"${GITHUB_OUTPUT}"
          jq . <<<"${matrix}"
        env:
          runner: ${{ inputs.runner }}
          texlive-version: ${{ inputs.texlive-version }}
  historic:
    needs: generate-matrix
    strategy:
      matrix:
        include: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
      fail-fast: false
      max-parallel: 4
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup TeX Live
        uses: ./
        with:
          cache: false
          version: ${{ matrix.texlive-version }}
