# Based on: https://github.com/actions/setup-node/blob/v4.0.0/.github/workflows/proxy.yml
name: E2E Proxy
on:
  push:
    branches: ['**']
    paths:
      - 'dist/**'
      - '!**/*.md'
      - action.yml
  workflow_dispatch:
permissions:
  contents: read
jobs:
  proxy:
    runs-on: ubuntu-latest
    container:
      image: >-
        ${{
          github.actor == 'nektos/act'
          && 'node:20.0'
          || 'ubuntu:latest'
        }}
      options: --dns 127.0.0.1
    services: # Requires `act >= 0.2.53` for local run.
      squid-proxy:
        image: ubuntu/squid:latest
        ports:
          - 3128:3128
    env:
      https_proxy: http://squid-proxy:3128
      http_proxy: http://squid-proxy:3128
    steps:
      - uses: actions/checkout@v4
      - name: Install requirements
        if: github.actor != 'nektos/act'
        run: |
          apt update
          apt install -y --no-install-recommends perl wget xz-utils
      - name: Setup TeX Live
        uses: ./
        with:
          cache: false
