name: E2E
on:
  push:
    branches: ['**']
    paths:
      - 'dist/**'
      - '!**/*.md'
      - action.yml
  workflow_dispatch:
permissions:
  contents: read
jobs:
  save-cache:
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    outputs:
      ubuntu-latest: ${{ steps.status.outputs.ubuntu-latest || '' }}
      windows-latest: ${{ steps.status.outputs.windows-latest || '' }}
      macos-latest: ${{ steps.status.outputs.macos-latest || '' }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup TeX Live
        id: setup
        uses: ./
      - name: Check that a new installation has been made
        if: fromJSON(steps.setup.outputs.cache-restored)
        run: exit 1
      - run: tlmgr version
      - name: Set output
        id: status
        shell: bash
        run: |
          echo "${MATRIX_RUNNER}=${MATRIX_RUNNER}" >> "${GITHUB_OUTPUT}"
        env:
          MATRIX_RUNNER: ${{ matrix.runner }}
  restore-cache:
    needs: save-cache
    if: |
      !cancelled() && (
        needs.save-cache.outputs.ubuntu-latest ||
        needs.save-cache.outputs.windows-latest ||
        needs.save-cache.outputs.macos-latest
      )
    strategy:
      matrix:
        runner:
          - ${{ needs.save-cache.outputs.ubuntu-latest }}
          - ${{ needs.save-cache.outputs.windows-latest }}
          - ${{ needs.save-cache.outputs.macos-latest }}
        exclude:
          - runner: ''
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup TeX Live
        id: setup
        uses: ./
      - name: Check that the cache is exactly matched
        if: ${{ !fromJSON(steps.setup.outputs.cache-hit) }}
        run: exit 1
      - run: tlmgr version
  delete-caches:
    needs: restore-cache
    if: >-
      always() &&
      github.actor != 'nektos/act'
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    continue-on-error: true
    steps:
      - uses: actions/checkout@v5
      - name: Install package
        run: >-
          npm ci
          --omit=dev
          --engine-strict=false
          --ignore-scripts
          -w packages/e2e
      - uses: actions/github-script@v8
        with:
          script: |
            const { deleteCaches } = require('@setup-texlive-action/e2e');
            await deleteCaches({ context, core, github });
  compile:
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup TeX Live
        uses: ./
        with:
          cache: false
          package-file: |
            **/tl_packages
            **/DEPENDS.txt
          packages: latex-bin
      - name: Compile
        shell: bash -e {0}
        run: |
          pdflatex -halt-on-error << 'EOF'
          \documentclass{article}
          \usepackage[language=english]{lipsum}
          \begin{document}
          \lipsum
          \end{document}
          EOF
